Repository datacarpentry/shell-genomics, pull requests merged in 2020-12, with the labels that each got.

#292 added subsection 'Command Prompt Editing' to Instructor Notes
  _extras/guide.md
Labels: type:discussion, type:enhancement, type:instructor guide

#294 Add information about combining flags to episode 02
  _episodes/02-the-filesystem.md
Labels: status:in progress, status:waiting for response, type:clarification

#291 Added an instruction for rm - Fixes issue #240
  _episodes/03-working-with-files.md
Labels: type:clarification

#299 Fix typo, add clarification
  _episodes/05-writing-scripts.md
Labels: type:clarification, type:enhancement
