Repository datacarpentry/shell-genomics, pull requests merged in 2020-06, with the labels that each got.

#280 relating to issues #171 and #269
  _episodes/02-the-filesystem.md
  _episodes/03-working-with-files.md
Labels: status:refer to cac, type:clarification, type:enhancement

#282 Following up on PR #276
  _episodes/06-organization.md
Labels: type:formatting

#283 Relating to issue #247
  reference.md
Labels: type:discussion

#285 relating to issue #256
  _episodes/03-working-with-files.md
  reference.md
Labels: type:enhancement

#286 fixes #284, for loops in objectives in episode 4
  _episodes/04-redirection.md
Labels: type:enhancement

#288 Issue #287 - removing redundancy in the 'Introducing the Shell' lesson.
  _episodes/01-introduction.md
Labels: type:clarification
